Scheduling/Scheduling/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("scheduler.urls"))
]

Scheduling/scheduler/urls.py
from django.urls import path
from . import views

urlpatterns= [
    path("", views.index, name="index"),
    path("login/", views.login_user, name = "login"),
    path("logout/", views.logout_user, name = "logout"),
    path("register/", views.register_user, name = "register"),
    path("about", views.about, name = "about"),
    path("employees", views.employees, name = "employees"),
    path("add", views.add_employee, name="add_employee"),
    path("schedule-structure", views.schedule_structure, name = "schedule-structure"),
    path("schedule-structure-add", views.schedule_structure_add, name = "schedule-structure-add"),
    path("schedule", views.schedule, name = "schedule"),
    path("schedule-add", views.schedule_add, name = "schedule-add"),
    path("change-preferences", views.change_preferences, name = "change-preferences"),
    path("employee/<int:id>", views.employee, name="employee"),
    path("schedule/<int:id>", views.single_schedule, name="single_schedule"),

    
    
]

Scheduling/scheduler/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Employee(models.Model):
    user = models.ForeignKey(User, related_name='employee', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50)
    working_hours_per_week = models.PositiveIntegerField(default=0)
    worked_hours = models.PositiveIntegerField(default=0)
    shifts_per_week = models.PositiveIntegerField()
    slug = models.SlugField(default="", null=False)

    def __str__(self) -> str:
        return f"{self.name}"
    
    def get_absolute_url(self):
        return reverse("employee", args=[self.id])
    
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

class Preferences(models.Model):
    employee = models.OneToOneField(Employee, on_delete=models.CASCADE)
    
    OPTION_ONE = 'OPTION_ONE'
    OPTION_TWO = 'OPTION_TWO'
    OPTION_THREE = 'OPTION_THREE'

    MY_CHOICES = [
        (OPTION_ONE, 'Gut'),
        (OPTION_TWO, 'Würde gehen, aber nicht gut'),
        (OPTION_THREE, 'Gar nicht'),
    ]

    monday_1 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)
    monday_2 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)
    monday_3 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)
    tuesday_1 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)
    tuesday_2 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)
    tuesday_3 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)
    wednesday_1 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)
    wednesday_2 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)
    wednesday_3 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)
    thursday_1 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)
    thursday_2 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)
    thursday_3 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)
    friday_1 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)
    friday_2 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)
    friday_3 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)
    saturday_1 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)
    saturday_2 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)
    saturday_3 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)
    sunday_1 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)
    sunday_2 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)
    sunday_3 = models.CharField(max_length=20,choices=MY_CHOICES,default=OPTION_ONE,)

    def __str__(self) -> str:
        return f"{self.employee.name}"


## CalenderWeek is a parent class for single Schedules
class CalenderWeek(models.Model):
    name = models.CharField(max_length=50, blank=False, unique=True)

    def __str__(self) -> str:
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse("single_schedule", args=[self.id])

    
class Schedule(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, null = True)
    calender_week = models.ForeignKey(CalenderWeek,on_delete=models.CASCADE,blank=True, null=True)
    monday_1 = models.BooleanField(default=False)
    monday_2 = models.BooleanField(default=False)
    monday_3 = models.BooleanField(default=False)
    tuesday_1 = models.BooleanField(default=False)
    tuesday_2 = models.BooleanField(default=False)
    tuesday_3 = models.BooleanField(default=False)
    wednesday_1 = models.BooleanField(default=False)
    wednesday_2 = models.BooleanField(default=False)
    wednesday_3 = models.BooleanField(default=False)
    thursday_1 = models.BooleanField(default=False)
    thursday_2 = models.BooleanField(default=False)
    thursday_3 = models.BooleanField(default=False)
    friday_1 = models.BooleanField(default=False)
    friday_2 = models.BooleanField(default=False)
    friday_3 = models.BooleanField(default=False)
    saturday_1 = models.BooleanField(default=False)
    saturday_2 = models.BooleanField(default=False)
    saturday_3 = models.BooleanField(default=False)
    sunday_1 = models.BooleanField(default=False)
    sunday_2 = models.BooleanField(default=False)
    sunday_3 = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.calender_week}: {self.employee}"

class WeeklyShiftPlan(models.Model):
    name = models.CharField(max_length=50)
    monday_1 = models.IntegerField()
    monday_2 = models.IntegerField()
    monday_3 = models.IntegerField()
    tuesday_1 = models.IntegerField()
    tuesday_2 = models.IntegerField()
    tuesday_3 = models.IntegerField()
    wednesday_1 = models.IntegerField()
    wednesday_2 = models.IntegerField()
    wednesday_3 = models.IntegerField()
    thursday_1 = models.IntegerField()
    thursday_2 = models.IntegerField()
    thursday_3 = models.IntegerField()
    friday_1 = models.IntegerField()
    friday_2 = models.IntegerField()
    friday_3 = models.IntegerField()
    saturday_1 = models.IntegerField()
    saturday_2 = models.IntegerField()
    saturday_3 = models.IntegerField()
    sunday_1 = models.IntegerField()
    sunday_2 = models.IntegerField()
    sunday_3 = models.IntegerField()

    def __str__(self) -> str:
            return f"{self.name}"

Scheduling/scheduler/views.py
from ortools.sat.python import cp_model
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .forms import NewEmployeeForm, NewWeeklyShiftPlanForm, SignUpForm, PickEmployeeForm, ChangePrefernecesForm
from .models import Employee, WeeklyShiftPlan, Schedule, CalenderWeek
from django.db.models import BooleanField
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
import utils

# Create your views here.

def index(request):
    if request.method == "POST":
        username= request.POST['username']
        password = request.POST['password']
        # Authenticate
        user = authenticate(request, username= username, password = password)
        if user is not None:
            login(request, user)
            messages.success(request, "Einloggen erfolgreich")
            return HttpResponseRedirect("./")
        else:
            messages.success(request, "Falscher Nutzername oder Passwort")
            return HttpResponseRedirect("./")
    return render(request, "scheduler/index.html")

def about(request):
    return render(request, "scheduler/about.html")

def schedule_structure(request):
    if request.user.is_authenticated:
        # The user is logged in. Render a user-specific page.
        context = {
            'username': request.user.username,
            'email': request.user.email,
        }
        return render(request, "scheduler/schedule_structure.html", {
            "weekly_shift_plans" : [],
        })
    else:
        # The user is not logged in. Render a standard page.
        weekly_shifts_plans = WeeklyShiftPlan.objects.all()
        return render(request,"scheduler/schedule_structure.html", {
            "weekly_shift_plans" : weekly_shifts_plans,
        })
    
def schedule_structure_add(request):
    if request.method == 'POST':
        form = NewWeeklyShiftPlanForm(request.POST)

        if form.is_valid():
            weekly_shift_plan = WeeklyShiftPlan(
                monday_1=form.cleaned_data['monday_1'],
                monday_2=form.cleaned_data['monday_2'],
                monday_3=form.cleaned_data['monday_3'],
                tuesday_1=form.cleaned_data['tuesday_1'],
                tuesday_2=form.cleaned_data['tuesday_2'],
                tuesday_3=form.cleaned_data['tuesday_3'],
                wednesday_1=form.cleaned_data['wednesday_1'],
                wednesday_2=form.cleaned_data['wednesday_2'],
                wednesday_3=form.cleaned_data['wednesday_3'],
                thursday_1=form.cleaned_data['thursday_1'],
                thursday_2=form.cleaned_data['thursday_2'],
                thursday_3=form.cleaned_data['thursday_3'],
                friday_1=form.cleaned_data['friday_1'],
                friday_2=form.cleaned_data['friday_2'],
                friday_3=form.cleaned_data['friday_3'],
                saturday_1=form.cleaned_data['saturday_1'],
                saturday_2=form.cleaned_data['saturday_2'],
                saturday_3=form.cleaned_data['saturday_3'],
                sunday_1=form.cleaned_data['sunday_1'],
                sunday_2=form.cleaned_data['sunday_2'],
                sunday_3=form.cleaned_data['sunday_3'],
                
                
                )
            weekly_shift_plan.save()
            return HttpResponseRedirect("./")
    else:
        form = NewWeeklyShiftPlanForm()
    return render(request, "scheduler/schedule_structure_add.html", {
        "form": form
    })


def employees(request):
    if request.user.is_authenticated:
        # The user is logged in. Render a user-specific page.
        context = {
            'username': request.user.username,
            'email': request.user.email,
        }
        employees = Employee.objects.filter(user=request.user)
        return render(request,"scheduler/employees.html", {
            "employees" : employees,
        })
    else:
        # The user is not logged in. Render a standard page.
        employees = Employee.objects.filter(user=None)
        return render(request,"scheduler/employees.html", {
            "employees" : employees,
        })

def employee(request, id):
    employee = get_object_or_404(Employee, pk=id)
    path = employee.name.lower().replace(" ", "_")
    return render(request, "scheduler/employee.html", {
        "employee" : employee,
        "path" : f"{path}.jpg",
    })

def add_employee(request):
    if request.method == 'POST':
        form = NewEmployeeForm(request.POST)

        if form.is_valid():
            employee = Employee(user= request.user, name=form.cleaned_data['name'],shifts_per_week=form.cleaned_data['shifts_per_week'])
            employee.save()
            return HttpResponseRedirect("./")
    else:
        form = NewEmployeeForm()
    return render(request, "scheduler/add_employee.html", {
        "form": form
    })

def change_preferences(request):
    form = ChangePrefernecesForm()
    return render(request, 'scheduler/change_preferences.html', {'form': form})


def schedule(request):
    if request.user.is_authenticated:
        # The user is logged in. Render a user-specific page.
        context = {
            'username': request.user.username,
            'email': request.user.email,
        }
        return render(request, "scheduler/schedule.html", {
                "calender_weeks": []
            })
    else:
        # The user is not logged in. Render a standard page.
        
        if request.method == 'GET':
            calender_weeks = CalenderWeek.objects.all()
            return render(request, "scheduler/schedule.html", {
                "calender_weeks": calender_weeks
            })
        else:
            return render(request, "scheduler/schedule.html")
    
def single_schedule(request, id):
    single_schedule = get_object_or_404(CalenderWeek, pk=id)
    # Get list of boolean field names in MyModel
    bool_fields = [field.name for field in Schedule._meta.fields if isinstance(field, BooleanField)]
    # For each object, sum over the values of the boolean fields
    sum_boolean = 0
    # For each object, sum over the values of the boolean fields
    sum_boolean_list = []
    for obj in single_schedule.schedule_set.all():
        sum_boolean = 0
        for field in bool_fields:
            
            if getattr(obj, field): # this gets the value of the field from the object
                
                sum_boolean += 1
        sum_boolean_list.append(sum_boolean)
    combined = zip(single_schedule.schedule_set.all(), sum_boolean_list)
    return render(request, "scheduler/calender_week.html", {
        "combined" : combined
        
    })

def schedule_add(request):
    if request.method == 'POST':
        form = PickEmployeeForm(request.POST)

        if form.is_valid():
            name = form.cleaned_data['name']
            employees = form.cleaned_data['objects']
            weekly_shift_plan = form.cleaned_data['single_object']
            # Do something with selected_objects here
            calender_week = CalenderWeek.objects.create(name = name)
            # get the number of employees
            num_employees = employees.count()
            print(num_employees)
            data = ((employee.name, employee.shifts_per_week) for employee in employees)
            num_shifts = 3
            num_days = 7
            num_weeks = 1

            ## Fixed assignment: (employee, shift, day).
            # This fixes the first 2 days of the schedule.
            fixed_assignments = []
            # Prohibited assignment: (employee, shift, day).
            prohibited_assignments = []
            # Request: (employee, shift, day, weight)
            # A negative weight indicates that the employee desire this assignment.
            requests = []
            # Employee 3 does not want to work on the first Saturday (negative weight
            # for the Off shift).
            #(3, 0, 5, -2),
            # Employee 5 wants a night shift on the second Thursday (negative weight).
            #(5, 3, 10, -2),
            # Employee 2 does not want a night shift on the first Friday (positive
            # weight).
            #(2, 3, 4, 4)
            for counter, employee in enumerate(employees):
                #Monday (counter, 0-2, 0)
                if employee.preferences.monday_1 == 'OPTION_THREE':
                    prohibited_assignments.append((counter,0,0))
                elif employee.preferences.monday_1 == 'OPTION_ONE':
                    requests.append((counter,0,0,-1))
                elif employee.preferences.monday_1 == 'OPTION_TWO':
                    requests.append((counter,0,0,2))
                if employee.preferences.monday_2 == 'OPTION_THREE':
                    prohibited_assignments.append((counter,1,0))
                elif employee.preferences.monday_2 == 'OPTION_ONE':
                    requests.append((counter,1,0,-1))
                elif employee.preferences.monday_2 == 'OPTION_TWO':
                    requests.append((counter,1,0,2))
                if employee.preferences.monday_3 == 'OPTION_THREE':
                    prohibited_assignments.append((counter,2,0))
                elif employee.preferences.monday_3 == 'OPTION_ONE':
                    requests.append((counter,2,0,-1))
                elif employee.preferences.monday_3 == 'OPTION_TWO':
                    requests.append((counter,2,0,2))
                #Tuesday (counter, 0-2, 1)
                if employee.preferences.tuesday_1 == 'OPTION_THREE':
                    prohibited_assignments.append((counter,0,1))
                elif employee.preferences.monday_3 == 'OPTION_ONE':
                    requests.append((counter,0,1,-1))
                elif employee.preferences.monday_3 == 'OPTION_TWO':
                    requests.append((counter,0,1,2))
                
                if employee.preferences.tuesday_2 == 'OPTION_THREE':

Scheduling/scheduler/templates/scheduler/about.html
{% extends 'scheduler/base.html' %}

{% block title %}
    Über uns
{% endblock title %}
{% block content %}
<h2>UniTransferKlinik</h1>
<p>
    Die UniTransferKlinik Lübeck befindet sich inmitten des wissenschaftlichen Herzens Lübecks. Mit dem Sitz auf dem Campus der technischen Hochschule Lübeck, der Universität zu Lübeck und des Uniklinikums Schleswig-Holsteins sind die Kommunikations­wege besonders kurz. Sie beschäftigt sich insbesondere mit Frage­stellungen rund um die Digitalisierung, vor allem bezogen auf die Medizintechnik 4.0. Hieraus resultierend stellt sich die UTK Aufgaben­stellungen aus dem Gebiet der Sicherheit und Zuverlässigkeit bei gleichzeitiger Vernetzung und Inter­operabilität. Zudem hat die Thematik der künstlichen Intelligenz einen großen Einfluss auf die Digitalisierung und bietet neuartige Lösungs­ansätze für alte Probleme, zum Beispiel bei der anhaltenden Pflege­krise. Besondere Schwerpunkte sind das Prozess­management, das unentbehrlich für ein gut laufendes Projekt ist und die Abwicklung der Zulassungs­prozedere neu entwickelter Produkte.
</p>
<p><a href="https://www.unitransferklinik.de/ueber">Internetseite</a></p>
{% endblock content %}

Scheduling/scheduler/templates/scheduler/add_employee.html
{% extends 'scheduler/base.html' %}

{% block title %}
    Neuer Mitarbeiter
{% endblock title %}

{% block content %}
<main>
    <p></p>
    <form  method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit">Hinzufügen</button>
    </form>
    <p></p>
    <form method="GET" action="{% url 'employees' %}">
        <button type="submit">Zurück</button>
</main>
    
{% endblock content %}

Scheduling/scheduler/templates/scheduler/base.html
{% load static  %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block  title %}{% endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% block css_files %}
    <link rel="stylesheet" href="{% static 'scheduler/styles.css' %}">
    {% endblock css_files %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}">Startseite</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'employees' %}">Mitarbeiter</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'schedule' %}">Schichtpläne</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'schedule-structure' %}">Dienstplanstruktur</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">Über uns</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Login</a>
              </li>

              {% endif %}
              
            </ul>
            
          </div>
        </div>
    </nav>

    {%block content%}{%endblock%}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

Scheduling/scheduler/templates/scheduler/calender_week.html
{% extends 'scheduler/base.html' %}

{% block title %}
Dienstplan
{% endblock title %}

{% block content %}

<h1>{{single_schedule.name}}</h1>
<table class="table table-striped table-hover table-bordered">
    <thead class="table-light">
    
        <tr>
            <th scope="col"></th>
            <th scope="col">Name</th>
            <th colspan="3">Montag</th>
            <th colspan="3">Dienstag</th>
            <th colspan="3">Mittwoch</th>
            <th colspan="3">Donnerstag</th>
            <th colspan="3">Freitag</th>
            <th colspan="3">Samstag</th>
            <th colspan="3">Sonntag</th>

        </tr>
        <tr>
            <th scope="col">#</th>
            <th scope="col"></th>
            <th scope="col">Früh</th>
            <th scope="col">Spät</th>
            <th scope="col">Nacht</th>
            <th scope="col">Früh</th>
            <th scope="col">Spät</th>
            <th scope="col">Nacht</th>
            <th scope="col">Früh</th>
            <th scope="col">Spät</th>
            <th scope="col">Nacht</th>
            <th scope="col">Früh</th>
            <th scope="col">Spät</th>
            <th scope="col">Nacht</th>
            <th scope="col">Früh</th>
            <th scope="col">Spät</th>
            <th scope="col">Nacht</th>
            <th scope="col">Früh</th>
            <th scope="col">Spät</th>
            <th scope="col">Nacht</th>
            <th scope="col">Früh</th>
            <th scope="col">Spät</th>
            <th scope="col">Nacht</th>
            <th scope="col">Schichten</th>
        </tr>
    </thead>
    <tbody>
        {% for schedule, sum_boolean_list in combined %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{schedule.employee.name}}</td>
            <td>{% if schedule.monday_1 %}X{% endif %}</td>
            <td>{% if schedule.monday_2 %}X{% endif %}</td>
            <td>{% if schedule.monday_3 %}X{% endif %}</td>
            <td>{% if schedule.tuesday_1 %}X{% endif %}</td>
            <td>{% if schedule.tuesday_2 %}X{% endif %}</td>
            <td>{% if schedule.tuesday_3 %}X{% endif %}</td>
            <td>{% if schedule.wednesday_1 %}X{% endif %}</td>
            <td>{% if schedule.wednesday_2 %}X{% endif %}</td>
            <td>{% if schedule.wednesday_3 %}X{% endif %}</td>
            <td>{% if schedule.thursday_1 %}X{% endif %}</td>
            <td>{% if schedule.thursday_2 %}X{% endif %}</td>
            <td>{% if schedule.thursday_3 %}X{% endif %}</td>
            <td>{% if schedule.friday_1 %}X{% endif %}</td>
            <td>{% if schedule.friday_2 %}X{% endif %}</td>
            <td>{% if schedule.friday_3 %}X{% endif %}</td>
            <td>{% if schedule.saturday_1 %}X{% endif %}</td>
            <td>{% if schedule.saturday_2 %}X{% endif %}</td>
            <td>{% if schedule.saturday_3 %}X{% endif %}</td>
            <td>{% if schedule.sunday_1 %}X{% endif %}</td>
            <td>{% if schedule.sunday_2 %}X{% endif %}</td>
            <td>{% if schedule.sunday_3 %}X{% endif %}</td>
            <td>{{ sum_boolean_list }}</td>
            
            

            
        </tr>
        {% endfor %}
    </tbody>
</table>



<p></p>
<form action="{% url 'schedule'%}" method="POST">
    {% csrf_token %}
    <button type="submit">Neuen Dienstplan erstellen</button>
</form>
<p></p>
    
{% endblock content %}

Scheduling/scheduler/templates/scheduler/change_preferences.html
{% extends 'scheduler/base.html' %}

{% block title %}
Dienstplan
{% endblock title %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>

{% endblock content %}

Scheduling/scheduler/templates/scheduler/employee.html
{% extends 'scheduler/base.html' %}

{% block title %}
    {{name}}
{% endblock title %}

{% block content %}
    <h1>{{employee.name}}</h1>
    <p>Arbeitsstunden pro Woche: {{employee.working_hours_per_week}}</p>
    <p>Bereits gearbeitete Stunden: {{employee.worked_hours}}</p>
    <p>Umrechnung in Schichten: {{employee.shifts_per_week}}</p>
    <p>{{path}}</p>
    <table class="table table-striped table-hover table-bordered">
        <thead class="table-light">
          <tr>
            <th scope="col"></th>
            <th scope="col"></th>
            <th colspan="3">Montag</th>
            <th colspan="3">Dienstag</th>
            <th colspan="3">Mittwoch</th>
            <th colspan="3">Donnerstag</th>
            <th colspan="3">Freitag</th>
            <th colspan="3">Samstag</th>
            <th colspan="3">Sonntag</th>
    
        </tr>
        <tr>
            <th scope="col"></th>
            <th scope="col">#</th>
            <th scope="col">Früh</th>
            <th scope="col">Spät</th>
            <th scope="col">Nacht</th>
            <th scope="col">Früh</th>
            <th scope="col">Spät</th>
            <th scope="col">Nacht</th>
            <th scope="col">Früh</th>
            <th scope="col">Spät</th>
            <th scope="col">Nacht</th>
            <th scope="col">Früh</th>
            <th scope="col">Spät</th>
            <th scope="col">Nacht</th>
            <th scope="col">Früh</th>
            <th scope="col">Spät</th>
            <th scope="col">Nacht</th>
            <th scope="col">Früh</th>
            <th scope="col">Spät</th>
            <th scope="col">Nacht</th>
            <th scope="col">Früh</th>
            <th scope="col">Spät</th>
            <th scope="col">Nacht</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row"></th>
                <td>Präferenz:</td>
                <td>{{employee.preferences.get_monday_1_display}}</td>
                <td>{{employee.preferences.get_monday_2_display}}</td>
                <td>{{employee.preferences.get_monday_3_display}}</td>
                <td>{{employee.preferences.get_tuesday_1_display}}</td>
                <td>{{employee.preferences.get_tuesday_2_display}}</td>
                <td>{{employee.preferences.get_tuesday_3_display}}</td>
                <td>{{employee.preferences.get_wednesday_1_display}}</td>
                <td>{{employee.preferences.get_wednesday_2_display}}</td>
                <td>{{employee.preferences.get_wednesday_3_display}}</td>
                <td>{{employee.preferences.get_thursday_1_display}}</td>
                <td>{{employee.preferences.get_thursday_2_display}}</td>
                <td>{{employee.preferences.get_thursday_3_display}}</td>
                <td>{{employee.preferences.get_friday_1_display}}</td>
                <td>{{employee.preferences.get_friday_2_display}}</td>
                <td>{{employee.preferences.get_friday_3_display}}</td>
                <td>{{employee.preferences.get_saturday_1_display}}</td>
                <td>{{employee.preferences.get_saturday_2_display}}</td>
                <td>{{employee.preferences.get_saturday_3_display}}</td>
                <td>{{employee.preferences.get_sunday_1_display}}</td>
                <td>{{employee.preferences.get_sunday_2_display}}</td>
                <td>{{employee.preferences.get_sunday_3_display}}</td>
                
            </tr>
        
          
        </tbody>
      </table>
      <a href="{% url 'change-preferences'%}" class="btn">Präferenzen ändern</a>
        
{% endblock content %}